### ISSUE TITLE
태그기능 한번 써봅시다

### ISSUE THREAD

**Issue by PartWorm** [sungbin5304/KUtils#1]
히스토리에 태그를 붙여서 버전을 표시할 수 있다는데, 지금 방법보다 좋을 거 같어요

**Comment by jisungbin** [comment]
의견 감사합니다.
v3때 태그를 이용하여 버전표시를 하겠습니다.

**Comment by PartWorm** [comment]
KUtils 2.0.js를 KUtils.js로 이름 바꾸고 기존 KUtils.js(버전 1.0)는 삭제하겠습니다.
결과적으로 1.0과 2.0 모두 KUtils.js라는 파일명을 쓰도록 하는 효과입니다.
그리고 2.0을 개발 시작하기 직전 커밋에 v1.0 태그를 달고, 2.0은 완성 안 된 것 같으니 dev 브랜치로 만들게요.
